import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./providers";
import { Toaster } from "../components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
